### ISSUE TITLE
The names of the players are not displayed when they are on the team

### ISSUE THREAD

**Issue by ghost** [vetustus/SimpleChat#2]
%player% shows nothing if the player is in the team

**Comment by rantuhin** [comment]
Thank you for your feedback! It will be fixed.

**Comment by rantuhin** [comment]
I fixed this in both versions of the game (MC 1.17 and  MC 1.16.5), but something tells me that I should add a placeholder for the prefix and suffix of the team, as well as the color of the nickname. 
Please respond to this comment.

**Comment by ghost** [comment]
I haven't had time to test the bug fix yet but yes adding the ability to change the prefix and suffix is a good idea and if you add RGB colors it will be a super mega good idea xD

**Comment by ghost** [comment]
and one more thing ... I think global chat doesn't work on 1.17 even if it's on true ... the only way to use the mod is to set local chat distance to 10000
