### ISSUE TITLE
Plans to update?

### ISSUE THREAD

**Issue by blacksythe** [vetustus/SimpleChat#7]
As this hasn't been updated in  8 months do you plan to update this to later mc versions?

**Comment by rantuhin** [comment]
Of course, I'm going to update this mod and other projects. However, I have very little time. I will try to do everything this week.

**Comment by blacksythe** [comment]
Many thanks for getting back to me so soon. I completely understand as time is something of a luxury for me too. I'm just considering what mods to use on a server I'm working on at a moment. As you can understand I didn't want to add something that wasn't getting updated any more. Thankyou for your reply.
